[package]
name = "ziggurat-ripple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.3"
toml = "0.5.9"

[dependencies.serde]
version = "1"
features = [ "derive" ]
