on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: basics

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain install stable --profile minimal
      - run: cargo check --all-targets

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain install nightly --profile minimal
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain install stable --profile minimal
      - run: rustup component add clippy
      - run: cargo clippy --all-targets -- -D warnings
