name: basics

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  core:
    uses: ziggurat/ziggurat-core/.github/workflows/check-and-lint.yml@main

  check-crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo check --features=crawler
