name: rippled

on:
  schedule:
    - cron: '0 6 * * *' # Every day at 6:00 AM UTC.
  push:
    branches:
      - reuse-workflow

jobs:
  install-rippled:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          pip install -Iv conan==1.59.0
          wget https://github.com/Kitware/CMake/releases/download/v3.16.3/cmake-3.16.3-Linux-x86_64.sh
          sudo sh cmake-3.16.3-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir
      - name: Clone rippled and set up conan
        run: |
          git clone https://github.com/XRPLF/rippled
          cd rippled
          git checkout master
          conan profile new default --detect
          conan profile update settings.compiler.cppstd=20 default
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Build rippled
        run: |
          cd rippled
          conan export external/snappy snappy/1.1.9@
          mkdir build
          cd build
          conan install .. --output-folder . --build missing --settings build_type=Release
          cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=build/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -j $(nproc)
      - uses: actions/upload-artifact@v3
        with:
          name: rippled-executable
          path: ./rippled/build/rippled

  install-ziggurat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-targets --no-run --features performance
      - uses: actions/upload-artifact@v3
        with:
          name: ziggurat-executable
          path: ./target/debug/deps/ziggurat_*

  test-rippled:
    runs-on: ubuntu-latest
    needs: [ install-ziggurat, install-rippled ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: rustup toolchain install stable --profile minimal
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/download-artifact@v3
        with:
          name: rippled-executable
          path: ./rippled
      - uses: actions/download-artifact@v3
        with:
          name: ziggurat-executable
          path: ./ziggurat
      - name: Enable openSSL legacy functions
        run: |
          cp /etc/ssl/openssl.cnf ./
          sed -i 's/^\#openssl_conf = openssl_init/openssl_conf = openssl_init/' openssl.cnf
          sed -i '/^\default = default_sect/a legacy = legacy_sect' openssl.cnf
          sed -i '/^\[default_sect\]/a activate = 1' openssl.cnf
          echo "[legacy_sect]" >> openssl.cnf
          echo "activate = 1" >> openssl.cnf
      - name: Run setup script
        env:
          OPENSSL_CONF: /home/runner/work/xrpl/xrpl/openssl.cnf
          RIPPLED_BIN_PATH: /home/runner/work/xrpl/xrpl/rippled
        run: |
          pip3 install xrpl-py
          chmod +x rippled/rippled
          ./tools/setup_env.sh
      - name: Prepare IP addresses
        run: sudo python3 ./tools/ips.py --subnet 1.1.1.0/24 --file src/tools/ips.rs --dev lo
      - name: Run ziggurat suite
        continue-on-error: true
        run: |
          rm ./ziggurat/*.d
          mv ./ziggurat/ziggurat_* ziggurat_test
          chmod +x ziggurat_test
          mkdir -p results/rippled
          mv results/rippled/latest.jsonl results/rippled/comparison.jsonl
          ./ziggurat_test --test-threads=1 --nocapture -Z unstable-options --report-time --format json > results/rippled/latest.jsonl
          cat results/rippled/latest.jsonl
      - uses: actions/upload-artifact@v3
        with:
          name: latest-result
          path: results/rippled/latest.jsonl
      - uses: actions/upload-artifact@v3
        with:
          name: previous-result
          path: results/rippled/previous.jsonl

  call-process-results-workflow:
    needs: [ test-rippled ]
    uses: zeapoz/zcash/.github/workflows/process-results.yml@reuse-workflow
    with:
      name: rippled
